### ISSUE TITLE
Add Support for IOS 10.x

### ISSUE THREAD

**Issue by sdyalor** [microsoft/fluentui-apple#100]
#### Platform
- [ x ] iOS
- [ ] macOS

#### Describe the feature that you would like added
SnapKit Supports IOS 10 and many other pods too, My company works with many IPADs 4th gen which are just capable to use IOS 10.3 :(

#### What component or utility would this be added to

Support for IOS 10.x 

#### Have you discussed this feature with our team, and if so, who

Not yet

#### Additional context/screenshots

README.md emphasizes support ios 11+

**Comment by harrieshin** [comment]
Hi @sdyalor . Our team has prioritized supporting iOS 11 and above to take advantage on the latest OS apis and swift compiler. Based on https://developer.apple.com/support/app-store/, most of our iOS customers are iOS 12 and above. Is it possible for you to fork this repo and make the necessary change for your sdk to support iOS 10?

**Comment by sdyalor** [comment]
Swift 5 compiles for ios 10, duno why you require ios 11 :(

**Comment by markavitale** [comment]
Hey @sdyalor , while it's true that iOS 10 is compatible with Swift 5, the limiting factor is more the complexity of supporting all the controls without APIs that are only available in iOS 11. Things like named colors, safe area insets and layout margins, directionalLayoutMargins, maskedCorners on layers, and much more are not available on iOS 10.

Supporting all of the same controls with the same behavior for iOS 10 means determining where we are relying on those APIs and re-implementing the same behavior without the APIs available, which can add complexity and bloat to our implementations and testing matrix for an OS that doesn't see a lot of usage.

If iOS 10 support is fully necessary for your use case, I second @harrieshin 's recommendation of forking and working around/removing the iOS 11 specific APIs.

**Comment by harrieshin** [comment]
no further plan so far. We are going to bump the min version support to iOS 13 so that we can write more swift ui componenets.
