### ISSUE TITLE
Signing for "MicrosoftFluentUI-FluentUIResources-ios" requires a development with Xcode 14

### ISSUE THREAD

**Issue by HariMohanAgrawal** [microsoft/fluentui-apple#1239]
### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: (fill this out if relevant)

#### Actual behavior:

Not running with Xcode 14.

#### Expected behavior:

Should work.
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No). No

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/applications affected: (if applicable)

**Comment by HariMohanAgrawal** [comment]
Please fix ASAP, I need to deliver my project, now i have updated Xcode 14, getting this issue. Signing for "MicrosoftFluentUI-FluentUIResources-ios" requires a development

**Comment by sophialee0416** [comment]
> Please fix ASAP, I need to deliver my project, now i have updated Xcode 14, getting this issue. Signing for "MicrosoftFluentUI-FluentUIResources-ios" requires a development

Hi @HariMohanAgrawal , could you send the full error message, or a screenshot of the error message that you are experiencing? Thanks!

**Comment by HariMohanAgrawal** [comment]
<img width="1221" alt="Screenshot 2022-09-15 at 11 13 24 AM" src="https://user-images.githubusercontent.com/19791652/190323752-f4895184-6859-4262-ad03-47cd1c4aed29.png">

**Comment by HariMohanAgrawal** [comment]
Please try with Xcode 14, in real device its not working.

**Comment by khdevi** [comment]
I was also facing the same issue. I had to choose Microsoft Coorporation Team manually to resolve it. @HariMohanAgrawal

**Comment by HariMohanAgrawal** [comment]
Sorry Microsoft Corporation Team is not showing inside Team drop down, Only my apple account team is showing, but we can not add our apple account inside team, It should be fix without doing anything.

@sophialee0416 Please check, before Xcode 14 its was working fine we can not set our team with third party library.

**Comment by HariMohanAgrawal** [comment]
@sophialee0416 
Any update, when it will fix, I need to deliver my app.

**Comment by sophialee0416** [comment]
@HariMohanAgrawal our team will need to discuss how to address this problem but I will return back to this thread once we reach a conclusion. Unfortunately I am not able to repro this issue on my end

**Comment by HariMohanAgrawal** [comment]
You can check this with Xcode 14, in fresh project just install this library, and run in device. Issue will generate.

**Comment by HariMohanAgrawal** [comment]
Hi,
This issue is not fixed yet, I am working on Xcode 14. But unable to run in device. Getting issue "Signing for "MicrosoftFluentUI-FluentUIResources-ios" requires a development"
