### ISSUE TITLE
Signing for "MicrosoftFluentUI-FluentUIResources-ios" requires a development with Xcode 14

### ISSUE THREAD

**Issue by HariMohanAgrawal** [microsoft/fluentui-apple#1347]
### Environment Information

- **Platform**:
  - [ ] iOS
  - [ ] macOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: (fill this out if relevant)

#### Actual behavior:
It needs to select my apple account in team inside pods.

Please check, before Xcode 14 its was working fine we can not set our team with third party library.

#### Expected behavior:
Without team it should work like other pods.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by harrieshin** [comment]
yes there is a new requirement of xcode 14. but also some known limitation of cocoapod that other people have found workaround to signed individual as target. https://github.com/CocoaPods/CocoaPods/issues/11402
