### ISSUE TITLE
TableViewCell memory leak in pod >= 0.8.0

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/fluentui-apple#1365]
There is a memory issue with `TableViewCell` when `TableViewCell` is kept in memory by `NotificationCenter` when the `TableViewCell` object should have been deallocated. This issue is reproducible on versions >= 0.8.0 (I can't reproduce it for 0.7.0 version). 

### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: CocoaPods; MicrosoftFluentUI/PopupMenu_ios pod version >= 0.8.0

### Please provide a reproduction of the bug:

[FluentUITableCellMemoryLeak.zip](https://github.com/microsoft/fluentui-apple/files/10016750/FluentUITableCellMemoryLeak.zip)

1. open attached project
2. run the project
3. tap "Show drawer" button
4. tap "Close" button
5. (optional) repeat 3-4 to see that NotificationCenter keeps strong references on all TableViewCells
6. click on "Debug Memory Graph" button in Xcode
7. check `TableViewCell` objects references in Xcode Memory Graph

![Screen Shot 2022-11-15 at 2 51 36 PM](https://user-images.githubusercontent.com/98852890/202043438-4e7d52b4-65ac-49a9-b4b1-7f327f08eea2.png)

#### Actual behavior:

`NotificationCenter` keeps strong references on `TableViewCell` objects.

#### Expected behavior:

No memory leaks.

### Priorities and help requested:
Products/applications affected: AzureCommunicationUICalling

**Comment by mischreiber** [comment]
Fixed in `main` and in released version 0.8.9. Fix will also be coming to the next 0.9.z release.
