### ISSUE TITLE
AvatarGroup - Thread Warning

### ISSUE THREAD

**Issue by jpeng-ms** [microsoft/fluentui-apple#1427]
### Environment Information

- **Platform**:
  - [X] iOS
  - [ ] macOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug:

when using avatar group in my project, it would trigger a lot of thread warnings when avatar group gets updated:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/109105353/205725525-b6f04ae5-ea9f-44ea-a3d5-f335e4f9e6f9.png">

I have created a simple project that reproduce this issue. All you need to do is run the project, and issue would be triggered (I have set up some dispatch group to update the content).

<img width="708" alt="image" src="https://user-images.githubusercontent.com/109105353/205725897-bc47f411-eecf-4c59-9d7d-c05edb95b5f1.png">

download simple code:
https://github.com/jpeng-ms/FluentTest

#### Actual behavior:

got the warnings printed on Xcode:
```
Publishing changes from within view updates is not allowed, this will cause undefined behavior.
```

#### Expected behavior:

no warnings

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/applications affected: (if applicable)

**Comment by jpeng-ms** [comment]
Hi @sophialee0416 would you mind to take a look when you got a chance?

**Comment by sophialee0416** [comment]
Thanks for creating the issue @jpeng-ms! I will take a look at this at my soonest availability.

**Comment by jpeng-ms** [comment]
Hi @laminesm, I am not sure why this was closed. I just tested it out the latest release (0.10.1), the issue is still reproducible:

https://github.com/jpeng-ms/FluentTest/tree/release-0.10.1

**Comment by jpeng-ms** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/109105353/211088282-d7cd9ea0-7a26-45fc-ba91-ceb18f3c53ff.png">
<img width="677" alt="image" src="https://user-images.githubusercontent.com/109105353/211088303-f27ee8ff-56ea-4ecc-b7f4-53a78cd01d0d.png">

**Comment by jpeng-ms** [comment]
@sophialee0416 @harrieshin can we reopen this since it's still reproducible?

**Comment by emlynmac** [comment]
Just confirming; this is still reproducible on 0.13.2

**Comment by sophialee0416** [comment]
Closing issue as it was resolved offline. The issue was that the SwiftUI-UIKit-SwiftUI sandwich was causing threading issues, so moving forward we recommend either using our UIKit wrapped controls in a UIKit environment, or our SwiftUI controls in a SwiftUI environment when possible.
