### ISSUE TITLE
SwiftUI Example

### ISSUE THREAD

**Issue by costoda-ey** [microsoft/fluentui-apple#153]
#### Platform
- [ x] iOS
- [x ] macOS

#### Describe the feature that you would like added
would love to see SwiftUI example as most new development is done on this platform.

#### What component or utility would this be added to
All controls and examples

#### Have you discussed this feature with our team, and if so, who
no

**Comment by Saadnajmi** [comment]
We have a SwiftUI Test app for macOS :D

**Comment by harrieshin** [comment]
please take a look at the vnext-prototype branch for lots of swiftui example which are coming soon!
