### ISSUE TITLE
value of type 'ControlTokenValue' has no member 'color'

### ISSUE THREAD

**Issue by anandhsonu1994** [microsoft/fluentui-apple#1732]
### Environment Information

- **Platform**:
  - [X] iOS
  - [ ] macOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug:
1. Add the FluentUI package into SwiftUI app
2. Build the app

#### Actual behavior:
Xcode throws below error on two files Divider.swift and DividerTokenSet.swift under FluentUI_os

Value of type 'ControlTokenValue' has no member 'color'

#### Expected behavior:
No error while building

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by laminesm** [comment]
This bug has been fixed on the latest versions of fluent so I'm closing this issue. Thanks for filing it!
