### ISSUE TITLE
Can't set titleColor and subtitleColor for a PopupMenuItem

### ISSUE THREAD

**Issue by microsoft-kshitij** [microsoft/fluentui-apple#1752]
### Environment Information

- **Platform**:
  -  iOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: Xcode version: 14.3

### Please provide a reproduction of the bug:

Create an instance of PopupMenuItem, try to change the color of title or subtitle by changing the titleColor or subtitleColor properties.

In the PopupMenuItem class also provided by FluentUI, I don't see these two fields being used, they're just exposed but not used I think (titleColor & subtitleColor).

#### Actual behavior:

The color doesn't get changed for title or subtitle

#### Expected behavior:

The color should get changed for title or subtitle

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)
Blocking

Products/applications affected: (if applicable)
Stream iOS App

**Comment by laminesm** [comment]
I couldn't reproduce the bug as both `titleColor` and `subtitleColor` are working properly. Which version of FluentUI are you using?

**Comment by microsoft-kshitij** [comment]
I am using 0.8.5
