### ISSUE TITLE
Cannot Access ViewModifiers from Project

### ISSUE THREAD

**Issue by schmiter** [microsoft/fluentui-apple#1790]
### Environment Information

- **Platform**:
  - [X] iOS
  - [X] macOS
- **Package version(s)**: Fluent version 0.14.0 - Swift Package Manager
- **Xcode and OS versions**: Xcode 14.3, MacOS Ventura 13.4

### Please provide a reproduction of the bug:
I was trying to use the `ShadowModifier` in `iOS/FluentUI/Core/SwiftUI+ViewModifiers.swift` and it cannot be accessed from our project. I tried:
 - using `.applyShadow(fluentTheme.shadow(.shadow02))` in a SwiftUI View
 - directly using `modifier(ShadowModifier(shadowInfo: shadowInfo))`

#### Actual behavior:
The error: "'applyShadow' is inaccessible due to 'internal' protection level" appears
The error: "Cannot find 'ShadowModifier' in scope"

#### Expected behavior:
Be able to access the view modifiers directly.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/applications affected:

**Comment by laminesm** [comment]
`applyFluentShadow` is now available for SwiftUI in [0.27.0](https://github.com/microsoft/fluentui-apple/releases/tag/0.27.0). Thanks!

**Comment by mischreiber** [comment]
[celebrate]     Mike Schreiber (HE/HIM) reacted to your message:
________________________________
