### ISSUE TITLE
TwoLineTitleView is cropped on landscape mode

### ISSUE THREAD

**Issue by amgleitman** [microsoft/fluentui-apple#1883]
### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: latest
- **Xcode and OS versions**: latest

### Please provide a reproduction of the bug:

1. Launch the FluentUI test app on an iPhone 14 or iPhone 14 Pro simulator **in landscape mode**.
2. In the Navigation section, look at an item with a two-line title view.

**Expected:** The title bar isn't cramped.

**Actual:** See screenshots below.

| <img width="898" alt="Screenshot 2023-07-03 at 1 44 24 PM" src="https://github.com/microsoft/fluentui-apple/assets/717674/277dd606-c193-4406-885a-185f013d6095"> | <img width="898" alt="Screenshot 2023-07-07 at 1 43 54 PM" src="https://github.com/microsoft/fluentui-apple/assets/717674/caaf69ec-f758-4db5-9496-f03217849d89"> |
|-|-|

### More Details

#1731 introduced a bug in a dependent of fluentui-apple where navigation views in drawer controllers don't render properly. As a result, #1761 was created to revert that bug in favor of a smaller but less bad bug that was tracked outside of GitHub. #1799 was created to help fix this, but it was deemed incomplete and other priorities took over, leading to a soft abandonment of the PR. This issue was created to track the bug specifically within GitHub.

**Comment by laminesm** [comment]
Fixed in #1891
