### ISSUE TITLE
Flutter support?

### ISSUE THREAD

**Issue by dmacan23** [microsoft/fluentui-apple#1892]
#### Platform
- [x ] iOS
- [x ] macOS

#### Describe the feature that you would like added

Not sure if this is the best place to ask. Feel free to point out the better channel and I'll ask there.

Are there any plans for adding Fluent 2 to Flutter? I know I'd love to try it out there

**Comment by anandrajeswaran** [comment]
No plans at the moment. For this particular repo, the focus remains on producing components which bring the Fluent design language to Apple's native UX frameworks (i.e UIKit/AppKit/SwiftUI).
