### ISSUE TITLE
Please make applyShadow to public 

### ISSUE THREAD

**Issue by cyberscorpion** [microsoft/fluentui-apple#1922]
#### Platform
- [x] iOS
- [ ] macOS

#### Describe the feature that you would like added

Please make `applyShadow` to public in extension. This will help us to apply fluent UI shadow to Swift UI View easily.
https://github.com/microsoft/fluentui-apple/blob/bcfab923aaf12ff1f6aa10387697594682a3630c/ios/FluentUI/Core/SwiftUI%2BViewModifiers.swift#L58C3-L60C6

#### What component or utility would this be added to

Applying a Fluent UI Shadow to a Swift UI View

#### Have you discussed this feature with our team, and if so, who

Yes, I have discussed this with team. And this will be helpful in using Fluent UI design more easily.

#### Additional context/screenshots

Example usages after making it public:
```
.applyShadow(shadowInfo: fluentTheme.shadow(.shadow02))
```

**Comment by laminesm** [comment]
`applyFluentShadow` is now available for SwiftUI in [0.27.0](https://github.com/microsoft/fluentui-apple/releases/tag/0.27.0). Thanks!
