### ISSUE TITLE
 Voice over is conveying irrelevant information while navigating to the textfield in the People Picker

### ISSUE THREAD

**Issue by tdesroch** [microsoft/fluentui-apple#256]
### Environment Information

- **Platform**:
  - [X] iOS
  - [ ] macOS

### Please provide a reproduction of the bug:
Enabled Voice Over and navigate to the PeoplePicker within the FluentUI test app.
VO swipe until your focus is on the empty BadgeField
Double-tap to select

#### Actual behavior:
VO will read out "zero width space"

#### Expected behavior:
VO shouldn't read out "zero width space" as it could be confusing to the user.

### Priorities and help requested:
Looking at the code emptyTextFieldString is being defined to the formal "0 width space" character "\u{200B}" so one could say that it's technically by design.  However, this seems to be an implementation detail of shouldChangeCharactersIn within the BadgeField inadvertently being exposed to VO users.

Requested priority: Normal

Products/applications affected: All consumers of BadgeField

**Comment by kubalani** [comment]
> ### Environment Information
> * **Platform**:
>   
>   * [x]  iOS
>   * [ ]  macOS
> 
> ### Please provide a reproduction of the bug:
> Enabled Voice Over and navigate to the PeoplePicker within the FluentUI test app.
> VO swipe until your focus is on the empty BadgeField
> Double-tap to select
> 
> #### Actual behavior:
> VO will read out "zero width space"
> 
> #### Expected behavior:
> VO shouldn't read out "zero width space" as it could be confusing to the user.
> 
> ### Priorities and help requested:
> Looking at the code emptyTextFieldString is being defined to the formal "0 width space" character "\u{200B}" so one could say that it's technically by design. However, this seems to be an implementation detail of shouldChangeCharactersIn within the BadgeField inadvertently being exposed to VO users.
> 
> Requested priority: Normal
> 
> Products/applications affected: All consumers of BadgeField

@tdesroch thanks for reporting your findings. I was able to replicate the problem on device but I am not sure if I understand the correct expected behavior. A simple replacement to empty string `""` instead of  `"\u{200B}"` does address the voice over issue. 

I am not sure if I understand implementation problems in `shouldChangeCharactersIn` of `BadgeView` related the problems in `PeoplePicker`.
