### ISSUE TITLE
Podspec in 0.1.16 specifies the iOS bundle for the Mac target

### ISSUE THREAD

**Issue by toadgee** [microsoft/fluentui-apple#274]
### Environment Information

- **Platform**:
  - [ ] iOS
  - [x] macOS
- **Package version(s)**: CocoaPods, podspec 0.1.16
- **Xcode and OS versions**: 12.2, 10.15.7

### Please provide a reproduction of the bug:

It looks like when I build 0.1.16 from cocoapods that it embeds the iOS bundle in the Mac framework, which then crashes when you try to use it.

#### Actual behavior:

crashes, looking for the fluentuiresources-mac bundle.

#### Expected behavior:

Not crashing

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yep

Requested priority: (Blocking, High, Normal, Low) Normal

Products/applications affected: (if applicable)

**Comment by Saadnajmi** [comment]
This should be fixed with 0.1.17

**Comment by toadgee** [comment]
yep, fixed thanks @Saadnajmi  and @HeyImChris
