### ISSUE TITLE
iPad DrawerController's bottom corner regression

### ISSUE THREAD

**Issue by harrieshin** [microsoft/fluentui-apple#289]
### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: 0.1.17
- **Xcode and OS versions**: (fill this out if relevant)

#### Actual behavior:

![bug](https://user-images.githubusercontent.com/20715435/97904530-7aef4b00-1cf5-11eb-99d0-b0cf1c32e2e2.png)

#### Expected behavior:
![expected](https://user-images.githubusercontent.com/20715435/97904580-8d698480-1cf5-11eb-8b87-d64751718893.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by rdeassis** [comment]
Fixed by #291
