### ISSUE TITLE
Rename repository default branch to "main"

### ISSUE THREAD

**Issue by markavitale** [microsoft/fluentui-apple#343]
#### Describe the work to be done
Microsoft is gradually moving to have its repositories use "main" as the default branch. Fluent UI Apple is no exception here and this issue tracks the work to migrate over to "main".

##### Migration
- Update all the CI/CD/pipelines to operate on both "master" and "main" branches
- Create a new "main" branch based off of the current default branch's latest commit
- Reassign any protected branch settings to the new "main" default branch from the former
- Update any open pull requests against the current default branch for the new "main" branch
- Update the default branch to the new "main" branch

##### Cleanup
- Delete the current default branch
- Update all the CI/CD/pipelines to remove the references to "master"
- Update all links/documentation to point to the main branch instead of the master branch
- Update the links on https://developer.microsoft.com/en-us/fluentui#/controls/ios to point to the main branch instead of the master branch.

#### Potential Impact
Any consumers of this library simply specifying "master" for Carthage consumption may* run into trouble. Instead, we recommend using a tagged commit for better stability.

\* I suspect that because [GitHub now redirects links to deleted branches to the default branch automatically](https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/), things may still work. 

#### Additional context/screenshots
See https://github.com/github/renaming for more context.

**Comment by Saadnajmi** [comment]
Also worth updating the internal documentation we have for the macOS controls in the repo

**Comment by markavitale** [comment]
Yep, that’ll happen in the “Update all links/documentation to point to the main branch instead of the master branch” cleanup phase.

**Comment by markavitale** [comment]
The last remaining bit of this work to update the public website is in review at https://github.com/microsoft/fluentui/pull/16978

**Comment by markavitale** [comment]
The website update is merged and now being cherry picked to the v7 (currently live) website. https://github.com/microsoft/fluentui/pull/16987. Going ahead and closing this issue as completed.
