### ISSUE TITLE
Add gesture convenience API for drawer view

### ISSUE THREAD

**Issue by kubalani** [microsoft/fluentui-apple#356]
#### Platform
- [X] iOS
- [ ] macOS

#### Describe the feature that you would like added

hmmmm... I think the client app shouldn't need to worry about this.
Isn't there a way to just attach the drawerController to a specific view/viewcontroller and let it read the gestures and take the appropriate actions?

_Originally posted by @rdeassis in https://github.com/microsoft/fluentui-apple/pull/344#r547524809_

**Comment by rdeassis** [comment]
The current DrawerController has a way to present itself through a gesture recognizer that is passed as a parameter from the host of the Drawer.

We should have a similar simple API that does not rely on the client app to have all the logic of presenting it.

Reference:

[@objc private func handlePresentingPan(gesture: UIPanGestureRecognizer)](https://github.com/microsoft/fluentui-apple/blob/7ec4cacc489f013b329952a616122a940da10583/ios/FluentUI/Drawer/DrawerController.swift#L642)
