### ISSUE TITLE
Add custom animation for DrawervNext

### ISSUE THREAD

**Issue by kubalani** [microsoft/fluentui-apple#357]
#### Platform
- [X] iOS
- [ ] macOS

#### Describe the feature that you would like added

Another issue you can file as a GitHub issue to be addressed after your first merge:

The current drawer presents the contents as you drag from the side instead of detecting the drag and presenting it entirely:

https://user-images.githubusercontent.com/68076145/102935613-585af200-445b-11eb-8a9c-99b48f8a66a7.mov

_Originally posted by @rdeassis in https://github.com/microsoft/fluentui-apple/pull/344#r547520295_

**Comment by rdeassis** [comment]
This is closely related to #356.
Once we can support a gesture recognizer for the presentation, the feature requested in this issue will also be accomplished.
