### ISSUE TITLE
Need a new release tag (0.1.24) for FluentUI

### ISSUE THREAD

**Issue by zetasq** [microsoft/fluentui-apple#376]
#### Platform
- [x] iOS
- [x] macOS

#### Describe the feature that you would like added

Version 0.1.23 was released 16 days ago. Since [this PR](https://github.com/microsoft/fluentui-apple/pull/368) got merged we can start consuming FluentUI into Outlook Mobile iOS client (we treat compile warnings as errors when building dependencies). But a new release tag (0.1.24) is needed. Do we have a plan for a new release in this or next week?

#### What component or utility would this be added to

N/A

#### Have you discussed this feature with our team, and if so, who

N/A

#### Additional context/screenshots

N/A

**Comment by zetasq** [comment]
CC @rdeassis

**Comment by rdeassis** [comment]
> CC @rdeassis

@zetasq we will have a new release this week.
