### ISSUE TITLE
how to set minimum and maximum date in calendar datepicker?

### ISSUE THREAD

**Issue by JayamuruganG** [microsoft/fluentui-apple#438]
#### Platform
- [x] iOS
- [ ] macOS

**Comment by JayamuruganG** [comment]
<img width="498" alt="Screenshot 2022-02-14 at 3 54 58 PM" src="https://user-images.githubusercontent.com/63097352/153846618-e630cdd5-baa2-4b48-9f18-b12f5ef41497.png">
while setting minimum start date ("CalendarConfiguration.default.referenceStartDate = Date()") .. app will be crash when clicking  uibutton.

**Comment by mischreiber** [comment]
Fixed in the `main` branch, and will be available in the next release (0.4.7).
