### ISSUE TITLE
Add EditorConfig file in repo 

### ISSUE THREAD

**Issue by kubalani** [microsoft/fluentui-apple#459]
This will help with code reviews to understand tab spaces and line limit. 

Sample .editorconfig file can be found here. 
https://github.com/editorconfig

I think Github thinks tabs are 8 spaces by default. You can fix that by adding a .editorconfig file

_Originally posted by @Saadnajmi in https://github.com/microsoft/fluentui-apple/pull/455#discussion_r585169113_

**Comment by harrieshin** [comment]
@Saadnajmi  i think actually https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/managing-your-tab-size-rendering-preference is a better solution that would work better for people?
