### ISSUE TITLE
Accessibility:  Not able to navigate to dates again in the DatePickerController after selecting a date in the previous month

### ISSUE THREAD

**Issue by bansalr-microsoft** [microsoft/fluentui-apple#511]
### Environment Information

- **Platform**:
  - [ ] iOS
  - [X] macOS
- **Package version(s)**: 0.2.4
- **Xcode and OS versions**: Xcode 12.2, Mac OS 11.2.3

### Please provide a reproduction of the bug:

In Date picker, select any date from the previous month and try again to navigate to the date region.
Observe we are not able to navigate to the date region again.

#### Actual behavior:
Toggle any date from the previous month in date picker, and try to navigate to date region again using tab/shift tab.
Observe we are not able to navigate to the date again.

#### Expected behavior:
All the time we should be able to navigate to the dates region in the Date picker.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/applications affected: Microsoft To Do

**Comment by Saadnajmi** [comment]
@lcapkovic in case you have insights

**Comment by lcapkovic** [comment]
This only repros in an NSPopover for me. When paging to any month, the new CalendarView doesn't seem to get added to the key view loop, so you can't navigate to it using tab anymore.

I found forcing a key view loop recalculation in the paging animation completion handler fixes it, but I'm not sure if that's the best solution.
The quick fix is to add `self.window?.recalculateKeyViewLoop()` at the end of the completionHandler in DatePickerView.swift line 343.

When presented in a popover, self.window will actually be the system-created NSPopoverWindow, not the main NSWindow where we have auto recalculating enabled. Maybe NSPopovers just don't auto recalculate the key view loop by default?

**Comment by anandrajeswaran** [comment]
fwiw I made a quick sample app that presents an NSPopover and the NSPopoverWindow has autorecalculatesKeyViewLoop set to true by default. Certainly possible something about animations is tricking the key view loop and it's calculating the loop before the animation has committed - maybe we could contrive a scenario like that to see if it's an Apple bug?

**Comment by chripear** [comment]
Prerequisite: check "Use keyboard navigation to move focus between controls" in System Preferences > Keyboard > Shortcuts
