### ISSUE TITLE
The safe area is not being considered while the gesture is moving the drawer

### ISSUE THREAD

**Issue by bazian3895** [microsoft/fluentui-apple#620]
### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: (fill this out if relevant)

#### Actual behavior:
The safe area is not being considered while the gesture is moving the drawer

#### Expected behavior:
Consider the safe area while the gesture is moving the drawer (decreasing size)

### Priorities and help requested:

Are you willing to submit a PR to fix? Can't:(

Requested priority: Normal

Products/applications affected: Power BI

**Comment by harrieshin** [comment]
I don't think I quite follow this bug. do you mind giving us more detail the issue you are facing?
