### ISSUE TITLE
Add focusGroupIdentifier and override canBecomeFocused for TabBarItemView for keyboard accessibility support for its subviews

### ISSUE THREAD

**Issue by DeepaliNemade839** [microsoft/fluentui-apple#714]
### Environment Information

- **Platform**:
  - [  ] iOS
  - [ ] macOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug:

https://office.visualstudio.com/APEX/_workitems/edit/5222461/
As mentioned in bug above, The create button view which is added over tabBarView is not becoming accessible via keyboard tab key when placed in the centre of the tabs. If the position of the button is changed to above the tab bar view or towards left/right edge of the tab bar view. it becomes accessible.

#### Actual behavior:

Union Create button not accessible via keyboard tab key.

#### Expected behavior:

Union Create button should be accessible via keyboard tab key while being placed in centre of the tab bar view.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/applications affected: Union

**Comment by harrieshin** [comment]
seem to be no longer a issue within fluent ui
