### ISSUE TITLE
Not able to build on Xcode 12.4 when adding framework for ios project using Cocoapods

### ISSUE THREAD

**Issue by ankitagg-ms** [microsoft/fluentui-apple#727]
### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: Cocoapods
- **Xcode and OS versions**: Xcode 12.4 and OS 11.6

### Please provide a reproduction of the bug:

- Fetch latest Library version ( 0.3.4 ) using cocoapods and try to build ios project with xcode 12.4

#### Actual behavior:

- It should work without any error.

#### Expected behavior:

Getting error in one of the method as can be seen in attached screenshot.
Working fine on xcode 13.

<img width="1192" alt="Screenshot 2021-09-30 at 3 59 39 PM" src="https://user-images.githubusercontent.com/81305950/135439115-c2a7c951-0d7e-425e-afca-82cba9209dcc.png">

### Priorities and help requested:

Requested priority: Blocking use of latest version, we are currently using 0.2.10

**Comment by mischreiber** [comment]
As documented in our `README`, new versions of Fluent UI require Xcode 12.5 or newer.
