### ISSUE TITLE
Breaking change of #707 does not respect semver

### ISSUE THREAD

**Issue by michaellan1** [microsoft/fluentui-apple#763]
Hello, I'm asking whether https://semver.org/ is expected for this framework?

Looks like in #707, UIKit-based `ActivityIndicatorView` was removed and replaced with a SwiftUI based one.

However, the version number only changed to `0.3.5` from `0.3.4`, with this breaking change.

**Comment by harrieshin** [comment]
Hi! yes we are trying to follow semver. "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable." We do try to communicate updates and minimized the public api changes as much as week can.
