### ISSUE TITLE
Certain Control Style Colors are no longer editable

### ISSUE THREAD

**Issue by sapunhan** [microsoft/fluentui-apple#84]
#### Platform
- [x] iOS
- [ ] macOS

#### Describe the feature that you would like added

In previous versions, we could update the background color properties of the switch Struct in the Colors class shown [here](https://github.com/microsoft/fluentui-apple/blob/master/ios/FluentUI/Core/Colors.swift). Now some of the properties are computed while others are mutable. Is it possible to have them all be mutable so we can edit the color properties of the switch control?

#### What component or utility would this be added to

The switch component in the Colors Class

#### Have you discussed this feature with our team, and if so, who
No

#### Additional context/screenshots

None

**Comment by harrieshin** [comment]
Hi @sapunhan, the design intent is that certain controls color will always follow in the theme of your app accent color or primary colors. For example in the test app, you can change the app color from shade of blue to shade of green, and you can see how different controls will follow the shade of colors. Also by implementing `public protocol ColorProviding `, you can change the app's accent color per UIWindow.
| Blue | Green | 
|-----------|:-----------:|
|![Simulator Screen Shot - iPhone Xʀ - 2020-05-29 at 17 32 08](https://user-images.githubusercontent.com/20715435/83315138-d8c1b900-a1d2-11ea-8fa1-c09eba90f102.png)|![Simulator Screen Shot - iPhone Xʀ - 2020-05-29 at 17 32 07](https://user-images.githubusercontent.com/20715435/83315142-dd866d00-a1d2-11ea-899c-d5d4edda5bc0.png)|
| ![Simulator Screen Shot - iPhone Xʀ - 2020-05-29 at 17 32 43](https://user-images.githubusercontent.com/20715435/83315155-ee36e300-a1d2-11ea-851c-70b363beca1c.png)|![Simulator Screen Shot - iPhone Xʀ - 2020-05-29 at 17 32 54](https://user-images.githubusercontent.com/20715435/83315167-fc84ff00-a1d2-11ea-9e23-4706d57e9fea.png) |

**Comment by harrieshin** [comment]
close this issue for now. please let us know if you have additional questions.
