### ISSUE TITLE
iOS version requirement inconsistent between SPM and CocoaPods

### ISSUE THREAD

**Issue by xnth97** [microsoft/fluentui-apple#845]
### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: 0.4.1, SPM

### Please provide a reproduction of the bug:

1. Add package with SPM
2. Build project

#### Actual behavior:

Get errors about APIs only available in iOS 14.0 or newer.

In podspec we have `s.ios.deployment_target = "14.0"` while in `Package.swift` the iOS version is marked as `.iOS(.v13)` (also in Readme). I think the version number should be consistent and maybe need to bump Package.swift version to .v14 to avoid the build errors.

#### Expected behavior:

Build without errors.

**Comment by mischreiber** [comment]
Thanks for pointing this out! It's resolved in `main` as of 7688a0d1509ecd4ebb8098603c0e47cdfa3e2dbf, and should be distributed in the next release (presumably `0.4.2`).

**Comment by xnth97** [comment]
@mischreiber Thank you for the quick fix! Will close the issue. It might also be great to update the requirements section in README as it's still referring to iOS 13.
