### ISSUE TITLE
Voiceover reads out "heading" for accessoryButton when TableViewHeaderFooterView starts off screen

### ISSUE THREAD

**Issue by CAllinsonMS** [microsoft/fluentui-apple#863]
### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: 0.1.21 - Cocoapods
- **Xcode and OS versions**: XCode 13.0 - iOS 15.0

#### Actual behavior:

It seems that voice over is reading out "heading" for an accessoryButton when a TableViewHeaderFooterView starts off screen and is then scrolled into view. This doesn't seem to happen to a TableViewHeaderFooterView if it is initially on screen, but it does occur for that TableViewHeaderFooterView if you scroll it off screen then back on screen.

#### Expected behavior:

Voice over does not read out "heading" for an accessoryButton in a TableViewHeaderFooterView.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/applications affected: Family Safety iOS App

**Comment by CAllinsonMS** [comment]
This issue was found in the Family Safety iOS App, which uses a much older FluentUI version:
'MicrosoftFluentUI', '~> 0.1.17'

I didn't see an issue for this (either open or closed), but testing the 0.4.1 demo app and looking at the TableViewHeaderFooterView source code, it seems that this issue has already been fixed via:
<img width="1048" alt="issue already fixed in later FluentUI version" src="https://user-images.githubusercontent.com/97644189/149395752-8d1cb4eb-0e27-451b-8fa7-89de159485fd.png">

**Comment by rdeassis** [comment]
Thanks for validating that @CAllinsonMS!
