### ISSUE TITLE
Need to disable the gesture that tapping the drawer's background to dismiss

### ISSUE THREAD

**Issue by Mishidexfc** [microsoft/fluentui-apple#95]
#### Platform
- [x] iOS
- [ ] macOS

#### Describe the feature that you would like added

Need to disable the gesture that tapping the drawer's background to dismiss. There are some scenarios that we only allow users to choose the options or tap the button in drawer to dismiss it. (For example, the drawer which contains the textfield, waiting for users to input something and tap the save button or cancel button).

#### What component or utility would this be added to

Add a property to control the tap-to-dismiss gesture in DrawerPresentationController.

#### Have you discussed this feature with our team, and if so, who

Not yet.

#### Additional context/screenshots

Although there's workaround that just remove the gesture in the subviews of presentationController's container. It's better to have a property to control it directly.

**Comment by Pratik-Chhajer** [comment]
@harrieshin this is fixed by #241 
Can we close this issue now?
