### ISSUE TITLE
Change Button Background color UIkit

### ISSUE THREAD

**Issue by Fdika24** [microsoft/fluentui-apple#953]
### Environment Information

- **Platform**:
  - iOS 14.0

### Please provide a reproduction of the bug:

i tried to set
button.backgroudColor = .systemPink
but the button stays dark blue

are there a way to change the button color or you cannot change the button color? thank you

**Comment by mischreiber** [comment]
Could you please identify which package version you are seeing this with?

**Comment by Fdika24** [comment]
the latest. i end up recoding the library so that I could add custom color
