### ISSUE TITLE
Changing Style of NavigationController

### ISSUE THREAD

**Issue by confusionhill** [microsoft/fluentui-apple#959]
I'm having a hard time checking on the demo about changing the navigation controller style

How do I set the style anyway? Thanks

**Comment by harrieshin** [comment]
what style are you looking for? https://github.com/microsoft/fluentui-apple/blob/main/ios/FluentUI.Demo/FluentUI.Demo/Demos/NavigationControllerDemoController.swift#:~:text=content.navigationItem.navigationBarStyle%20%3D%20style

**Comment by Fdika24** [comment]
are there a method that i can use to change the style? that's what I'm looking for

**Comment by harrieshin** [comment]
what is the style you like to change it to?

**Comment by harrieshin** [comment]
close for stale isse.
