### ISSUE TITLE
Is it possible to make personaSuggestionsView, personaListView in PeoplePicker public?

### ISSUE THREAD

**Issue by kiagrawal** [microsoft/fluentui-apple#97]
#### Platform
- [x] iOS
- [ ] macOS

#### Describe the feature that you would like added

I would like to get personaSuggestionsView, personaListView inside PeoplePicker as public so that I can modify the view(add label in between views, modify spacing).

Also, if searchDirectoryState in PersonaListView is accessible outside, we can directly have searchDirectory spinner showing depending on usage.

#### What component or utility would this be added to

PeoplePicker, PersonaListView

#### Have you discussed this feature with our team, and if so, who

No, would like to discuss with someone and know if it is possible.

**Comment by lugonzal** [comment]
Fixed
