### ISSUE TITLE
Carousel view with bullet list on bottom (Usually used to show Onboarding Tutorial) : iOS 

### ISSUE THREAD

**Issue by ankitagg-ms** [microsoft/fluentui-apple#975]
#### Platform
- [x] iOS
- [ ] macOS

#### Describe the feature that you would like added

Carousel view with bullet list on bottom and way to add multiple screens. (Handle both portrait and landscape mode)

#### What component or utility would this be added to

iOS UI

#### Additional context/screenshots
![Screenshot 2022-04-21 at 10 07 19 PM](https://user-images.githubusercontent.com/81305950/164508964-3a930a09-377a-4213-a01e-f6baec4d0b2a.png)

**Comment by harrieshin** [comment]
Hello! The recommendation is to use Apple's native uipagecontrol directly. https://developer.apple.com/documentation/uikit/uipagecontrol
