### ISSUE TITLE
SearchDirectory results count in PersonaListView does not get refreshed

### ISSUE THREAD

**Issue by kiagrawal** [microsoft/fluentui-apple#98]
### Environment Information

- **Platform**:
  - [x] iOS
  - [ ] macOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug:

Go to PeoplePicker, type a name and click on search directory button. Note the count of results returned. Now add another name or delete a char(don't remove all the typed characters) and the results count can be seen as same.

#### Actual behavior:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/67058720/85118247-b6edac00-b23d-11ea-9ee5-255ea202c7d1.png">

#### Expected behavior:

Either update search count or change searchDirectoryState back to idle. It can also be helpful if personaListView in PeoplePicker is made public/open.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: (Blocking, High, Normal, Low) High

Products/applications affected: (if applicable) Lists iOS

**Comment by lugonzal** [comment]
@kiagrawal I believe you fixed this, thanks!
